### ISSUE TITLE
[Bug] Nova is unable to passthrough Dolby TrueHD on Android 12

### ISSUE THREAD

**Issue by branches78** [nova-video-player/aos-AVP#1040]
### Problem description

My device (Homatics Box R 4K Plus) has Dolby TrueHD playback and passthrough support as well as my Samsung TV through the HDMI port and when I try to forward or rewind videos with that codec, the app freezes for a moment and then it renders the device completely unusable, I can't even watch videos on YouTube after that so I have reboot the device to fix it.

### Steps to reproduce the issue

N/A

### Your phone/tablet/androidTV model

Homatics Box R 4K Plus

### Operating system version

Android 12

### Application version and app store

Version 6.2.46 from github

**Comment by courville** [comment]
Just out of curiosity, if in nova settings you disable Dolby Vision, is the video playing correctly (apart from the colors)?

**Comment by Philofil92** [comment]
Hello, if it's any consolation...There are several incidents indicating a problem with "Dolby TrueHD" and "Dolby TrueHD Atmos" on this forum...Between enabling "passthrough" 1/Disabled 2/Mode 1 and 3/ Mode 2 is not very clear... On my smart TV, to have the decoding taken into account DTS and DTS HD, I have to activate mode 2 and force audio passthrough, but one track TrueHD crashes Nova like you! If I deactivate passthrought, True HD seems to work, but I no longer have DTS and DTS HD... A priori the management of sound tracks on Nova is very complicated and the problem dates from the beginning because it was designed in a strange way...I don't have my Smart TV available at the moment, but you can do a test with "Just Player" which takes it into account according to my information. Or you have to restart here, but you shouldn't be in a hurry, because there are still incidents dating back to 2018 that are still not resolved...I don't know at all what their criteria are for resolving their incidents here ...

**Comment by phhusson** [comment]
> I don't know at all what their criteria are for resolving their incidents here

Like any OSS developer, the biggest criteria is whether we can reproduce it.

**Comment by Philofil92** [comment]
English is not my natural language, so forgive me in advance if I didn't understand it well... But, if you tell me that you have to manage as a developer to reproduce the problem, this one is easy to reproduce, you set Nova to "Pass-Trought" activated in mode 2, for DTS and DTS HD MA detection (this is mandatory for the correct detection of these tracks), you send a Dolby True HD track or Dolby True HD Atmos, you launch Nova and it "crashes..."

**Comment by branches78** [comment]
Yesterday, the Homatics Box R 4K Plus received an update with a security patch dated december 5th 2023 and now Dolby TrueHD is not passing through anymore but it's getting decoded to stereo PCM, the rest of the audio codecs passed through correctly though.

Current audio issues with Nova on Android 12 are:

- Multichannel PCM is getting downmixed to stereo.

- Dolby TrueHD is now getting decoded as stereo PCM.

- The issues when passthrough is OFF in the app, which are already explained here: https://github.com/nova-video-player/aos-AVP/issues/953.

It doesn't matter if the box is connected directly to an AV receiver or when using the EARC port when the box is connected directly to my Samsung TV.

**Comment by courville** [comment]
@Philofil92 "it just crashes" does not account for the fragmentation of the Android ecosystem.
Just tried on an nvidia shield passthrough to my samsung soundbar and... sadly it works. 
It is true though that I am more using multichannel AAC and not often passthrough since I prefer the simplicity and reliability of mutichannel PCM.

EDIT: checked on 4 different files

**Comment by Philofil92** [comment]
No! I'm sorry, Dolby TrueHD and Dolby TrueHD Atmos never worked and are not detected correctly on Nova!
As "branches78" and myself say... Besides, I had already opened an incident for this problem
 01/12/2022 Dolby TrueHD and Dolby Atmos #738 04/07/2023 Dolby TrueHD and Dolby TrueHD Atmos detection and display bug!!! #495 10/29/2023 Dolby TrueHD and Dolby TrueHD Atmos detection and display bug!!! #495
and I'm going to open another incident for a "Flac" playback problem on 12/21/2022 Systematic video/audio synchronization problem for the "Flac stereo 48000HZ" sound track #1026, I know it's not easy for you, I never put pressure on you, but Nova is angry with the sound...well, he has trouble managing everything easily!!!

**Comment by branches78** [comment]
Unlike you @Philofil92 Dolby TrueHD with and without Dolby Atmos has always been working for me on the Homatics Box R 4K Plus until recently, when the latest security patch was applied.

I wonder where are you trying to play TrueHD, is it from a TV?, because as far as I know, smart TVs don't passthrough TrueHD nor DTS-HD MA from apps installed in the TV, instead, it only works when using the HDMI ports, that's how my current Samsung TV works, I don't know if other brands already bypassed this limitation imposed by Dolby (I imagine it was by them) like your TV, please clarify that.

**Comment by courville** [comment]
@Philofil92, you get my comments wrong I think.
I am not denying the fact that you have an issue with Dolby TrueHD.
What I am saying is that it might not work on your device but it works on other devices.
We do not have all the devices to test on, sometimes we buy some on our own funds to troubleshoot issues.
You have to understand that Android is a fragmented ecosystem that requires alignment of SoC vendor deliveries, proper integration and work around Android framework flaws plus some nova bugs fixing as well to get a video player working.
Nova is open-open source maintained by a couple of individuals on their spare time...
Sorry to hear that our work upsets you.

**Comment by branches78** [comment]
> You have to understand that Android is a fragmented ecosystem that requires alignment of SoC vendor deliveries, proper integration and work around Android framework flaws

There's the good, the bad and the ugly about Android, and that's definitely the ugly about Android as a whole.

**Comment by Philofil92** [comment]
I'm not trying to read...But I read DTS and DTS HD tracks and Dolby Atmos correctly (I have the decoding information displayed on the TV screen) on my TCL 65C825 Smart TV, and as this one also supports Dolby TrueHD and Dolby TrueHD Atmos, it should too if Nova supported this format too!

**Comment by branches78** [comment]
@Philofil92 one thing is what the the TV shows and another what it actually passes through the EARC port, if your TV actually has an EARC port then it should passthrough all supported codecs when using the HDMI ports only and not when using internal apps, do you have a computer that you can use to test and confirm what I'm saying?.

**Comment by Philofil92** [comment]
My nephew cries with his Samsung UE75H6400 at €2750 when he sees what I manage to decode with mine at €1000 and not him...I grant him for the sake of honesty that he has a more beautiful image than me, but at what cost?

Sorry! There's nothing to test or confirm...once you've understood one thing! You! You have a Samsung TV plus a Homatics Box R 4K Plus and Nova external box.

I have a Smart Google TV Android and Nova, and all the video and audio components and codecs are integrated directly on the motherboard, and when a "signal" arrives from any source, I get a notification on the screen! If I send a movie in Dolby Vision, I get the "Dolby Vision" indicator briefly displayed on the screen.
For audio it's the same, if I send a film in Dolby, DTS or DTS HD, Atmos...etc, I get a brief display of a light to indicate which sound track it is...And for TrueHD or TrueHD Atmos, there, it's simple, Nova crashes (Option pass through forced and mode 2 activated). If I remove the forced pass through and mode 2, Nova no longer crashes...(but given the dynamics, it's certainly not TrueHD) and decoding of DTS and other tracks is no longer possible!

After all, I'm not here to annoy the developers, I'm just kindly trying to point out problems when I find them, to help Nova grow... 3 weeks ago, I discovered a bug concerning a problem with "Flac" audio playback, so I pointed it out..... Even though I'm in IT, other than development, I can imagine that it can't be easy for them, especially as they don't have all the so-called compatible equipment to do their tests.

Just one piece of information I received recently, but which I can't confirm because I'm away from my smart TV for a few weeks, Just Player v0.151 and higher
correctly decodes TrueHD and TruHD Atmos

**Comment by branches78** [comment]
@Philofil92 I understand now, I though you had a passthrough issue but it's a decoding issue what you are facing with the app.

**Comment by branches78** [comment]
Looks like this is a problem of Dolby TrueHD on the box and not an specific issue with Nova, I experienced it with Emby as well.

**Comment by branches78** [comment]
So I was able to find out that Dolby TrueHD is passing through when the "force passtrough audio" is turned ON but it doesn't passthrough when it's OFF by decoding the audio to stereo PCM, therefore, I was finally able to get a log so you can finally fix this problem for good.

[Dolby TrueHD not working on Nova.log](https://github.com/nova-video-player/aos-AVP/files/15265125/Dolby.TrueHD.not.working.on.Nova.log)

**Comment by branches78** [comment]
I would say that "force passthrough" is an option to allow Dolby TrueHD to passthrough when it's ON and to decode it to PCM when it's OFF, it's just that it should have a different name since that's the ONLY audio codec that doesn't passthrough when it's OFF when using "Mode 2", just saying.

@Philofil92 please open a separate bug report for your issue since this one was for a different reason, I will close it because, like I just said above, the option should have a different name, there is nothing wrong with it.

**Comment by courville** [comment]
@branches78 "force passthrough" is an option that when audio passthrough mode is selected will not check the EDID of the AV receiver and apply passthrough whatever the codec is used.
Not forcing passthrough will account for claimed capabilities of the AV received before doing it and reverting to PCM decode otherwise.

**Comment by branches78** [comment]
> Not forcing passthrough will account for claimed capabilities of the AV receiver before doing it and reverting to PCM decode otherwise.

Does the above mean that the option is broken in that regard?, both, my device have TrueHD passthrough and the AV receiver has TrueHD decoding, therefore, when the option is OFF, TrueHD should passthrough because the EDID detect that both devices have support, this was working before in a previous version I really don't know, hence my concern.

**Comment by branches78** [comment]
> [Dolby TrueHD not working on Nova.log](https://github.com/nova-video-player/aos-AVP/files/15265125/Dolby.TrueHD.not.working.on.Nova.log)

I left this log on may 9th so you could take a look.
