### ISSUE TITLE
[Bug]: numerous "testCanWriteNova.tmp" created then deleted on network drives

### ISSUE THREAD

**Issue by phil-hhh** [nova-video-player/aos-AVP#1048]
### Problem description

Hi, since latest updated I have hundreds of "testCanWriteNova.tmp" added then deleted on the Synology NAS I use to stock media, while accessed by NovaPlayer on my Google TV

This heavily pollutes NAS logs and interferes with some personal cleaning scripts.

### Steps to reproduce the issue

Network & Files -> Network -> Shared Folders (SMB) -> connect to any drive available

In my case, the "recycle" folder on my NAS gets cluttered with thousands of "testCanWriteNova.tmp" files, 1 or 2 for absolutely every folder existing on the NAS

### Your phone/tablet/androidTV model

Chromecast HD

### Operating system version

Android TV 12

### Application version and app store

6.2.46 (20240105.1748) via Google Play

**Comment by courville** [comment]
Indeed, I added this since jcifs-ng cannot determine if a directory is writeable without actually writing a file (recommended way)... I understand the concern. I guess I will remove this and assume canWrite always...

Reference https://github.com/AgNO3/jcifs-ng/issues/219 and https://github.com/nova-video-player/aos-FileCoreLibrary/commit/9aa1077d3c6e4e6fd1dfd1baa9462a6a759e333a

**Comment by courville** [comment]
Will be removed in next release.

**Comment by courville** [comment]
@phil-hhh this https://github.com/nova-video-player/aos-AVP/releases/tag/v6.2.49 release will fix your issue.

**Comment by phil-hhh** [comment]
wooooooow, millions of thanks for the rapidity, really appreciated !

Issue indeed fixed
