### ISSUE TITLE
Version numbers

### ISSUE THREAD

**Issue by JJD2K** [nova-video-player/aos-AVP#108]
I am confused now.
How you just released 3.5, while you have already released 4.1?
Why some releases like 4.4 do not have APK file?
I am really confused. 
Also it would be good to have the app version info in the settings so that one can check which version is running.

Also after 3.2 the decoding gets worse and worse...I do not know if it is an ffmpeg issue or what.

**Comment by courville** [comment]
Consider that we have various development tracks https://github.com/nova-video-player/aos-AVP/milestones
Next release is on v3.x (incremental).
All new developments are on api28 branch that is still unstable and requires development.
Decoding performance is the same on 4.x and 3.x.
On 3.5 software decoding form pre-M Android version is fixed.
Since 3.3 ffmpeg has been upgraded but frankly ffmpeg is used on modern hardware for only the parsers and platform hardware decoding is always used.
