### ISSUE TITLE
4.x and 3.x simultaneous install

### ISSUE THREAD

**Issue by JJD2K** [nova-video-player/aos-AVP#115]
While I am glad to test 4.x releases for you it is a pain in the ass to uninstall it to go to older version and reconfigure, reindex all.
Can you make it possible to install 3.x and 4.x releases simultaneously? Maybe different name - Nova 4 etc.

**Comment by courville** [comment]
It is nice to have a dedicated tester indeed.
The problem I have is that since it is the same package, it shares the same resources and to have simultaneous installs it would be mean to create a separate package.
This would prevent also people to upgrade...
Not easy request...
However I had no problem to install 4.x over 3.x and having 3.x over 4.x (via adb install -r file.apk).

**Comment by JJD2K** [comment]
I am installing via old version of ESFileExplorer (without the bloat) via Package Installer.
If I try to install 3.2 over 4.2 it says that the package is corrupt.
About upgrading one can delete 3.x after installing 4.x, but if it is a big issue ok.
Suggested it as it seems 4.x is developed as a separate branch anyway.

**Comment by JJD2K** [comment]
I tried this again and now it is working - do not know what happened the first time.
3.6 is quite slower decoding than 3.2 though and the audio menu is in front of the subs one.

**Comment by courville** [comment]
This will require some changes in the app that will prevent easy merge of branches.
This is not desired.
Sorry but I will not do it.
It is possible to install 4.x over 3.x via adb install -r
It is possible to install 3.x over 4.x via adb install -r
It is thus probably related to ESFileExplorer which is a foreign application
