### ISSUE TITLE
[Bug]: No Channels on Onn 4K Android TV running Android 12 

### ISSUE THREAD

**Issue by martinikem** [nova-video-player/aos-AVP#1163]
### Problem description

I updated to Android TV 12 on my Walmart owned Onn 4K Android TV with Projectivity Launcher and i noticed that i am no longer able to add Nova Video Channels (Movie, Recently Played, TV Shows, Animations etc) to my homescreen as i could previously on Android TV 10. 

I was wondering if there were any changes to Android or your app that brought about these changes. This issue seems to be restricted to Nova Video Player as Smart Tube and Cloudstream which i have installed on my TV box appear to be unchanged since the update and are able to have their channels show up in the homescreen.

### Steps to reproduce the issue

Go to the Homescreen and try to add channels, the channels seemed grayed out.
![PXL_20240324_171331848](https://github.com/nova-video-player/aos-AVP/assets/37476267/ed0153e9-ca9d-4a97-b259-88843b8441c5)
![PXL_20240324_171457541](https://github.com/nova-video-player/aos-AVP/assets/37476267/3b932d6e-a84a-44a5-9d30-7ce0e0762f28)

### Your phone/tablet/androidTV model

Onn 4K Android TV

### Operating system version

Android 12

### Application version and app store

6.2.57 ( Play Store)

**Comment by Manodragon** [comment]
I am having the same issue in 2026 on my nvidia Shield TV Pro

**Comment by malmr** [comment]
Why was this closed @martinikem ?

**Comment by martinikem** [comment]
I didn't closed it. I'm guessing it was closed for me.

**Comment by courville** [comment]
We've made a couple of fixes to the TV channels (home screen rows) code since this was reported that may address the "channels greyed out / can't be added" symptom:

- a3cd191e — fix: refresh TV channels after async channel creation (channel creation/population lost guaranteed ordering after an internal AsyncTask migration, which could leave channels empty)
- 2ca20c30 — Fix NullPointerException in PrepareChannelsTask during channel initialization (a crash mid-initialization could leave the channel list in a broken/empty state)

Both are included starting with 6.4.x builds. @Manodragon @malmr could you update to the latest version and confirm whether channels can be added again on your devices?
