### ISSUE TITLE
[FEAT]: selection of the language for the interface

### ISSUE THREAD

**Issue by Tepee-me** [nova-video-player/aos-AVP#1235]
### Description

I have Nova installed on a Chinese projector (Mi projector) with Android inclued. This projector has only Chinese and English proposed for the overall system. So I have chosen English on it.
Then Nova, when installed, automatically propose an English interface, corresponding to the OS language. But as I am French, I would like to change it to French, but none is proposed.
**Could it be possible to add in Settings section the chose of the Interface language for Nova ?**

**Comment by courville** [comment]
I understand the need and it makes sense (for devices supporting only english like chinese version of the mi projector, for devices where chinese is absent e.g. firetv etc.).
I tried to give it a try and it turns out that it is trickier than expected (to get all the activities/fragments etc. to update their language).
I will push a development branch and see how far I can get.

**Comment by courville** [comment]
See https://github.com/nova-video-player/aos-Video/tree/dev/localeSetting commits

**Comment by Tepee-me** [comment]
I just updated to the v6.3.4 and see that you added the option !
Thank you, it is much easier for my child !
You rock !
