### ISSUE TITLE
Grey bars issue

### ISSUE THREAD

**Issue by lys1980** [nova-video-player/aos-AVP#270]
When reproducing some videos the black bars turn grey, I have a Sony XF90 Android TV.
It is really quite ugly and distracting. Any chance to make them pure black?

Thanks

**Comment by courville** [comment]
Are you using software decoding or hardware decoding?
Could you please disclose the format of the video (exact resolution and codec) or even better share the video that is causing issues?

**Comment by courville** [comment]
Picture of the issue would help too.

**Comment by hannibalxking** [comment]
hi everyone, the issue is known by all the sony bravia user, that's happen when we watch a hdr video.
![IMG_0972](https://user-images.githubusercontent.com/22693971/73606394-270ad680-45aa-11ea-9265-d94d658da273.JPG)

i found some link for the issue that can be exploited for the player 

https://github.com/CiNcH83/bravia_atv2/issues/44
https://github.com/MrMC/mrmc/commit/e686c40a50c8474300571dc62b0a5a8c3b519604

I hope that helps because i use nvp too with a bravia tv and i really like the player its lite and do the job ^.^

**Comment by courville** [comment]
> hi everyone, the issue is known by all the sony bravia user, that's happen when we watch a hdr video.
> i found some link for the issue that can be exploited for the player
> [CiNcH83/bravia_atv2#44](https://github.com/CiNcH83/bravia_atv2/issues/44)
> [MrMC/mrmc@e686c40](https://github.com/MrMC/mrmc/commit/e686c40a50c8474300571dc62b0a5a8c3b519604)

Thanks for sharing this tip. I tried to adapt it to nova. Could you please check the resulting apk and report if it helps?
https://drive.google.com/open?id=1mPNtoKnkcDam8fzBGwXbrP8ghyGCjCRt

**Comment by hannibalxking** [comment]
oh that's quick i tried wright now 

edit: well that work like a charm i tested all my hdr contents all have black bar im happy no need plex or kodi anymore.
thank you for all the bravia tv user you make my day.
