### ISSUE TITLE
Choppy 1080p playback in latest versions on Sony TV

### ISSUE THREAD

**Issue by JJD2K** [nova-video-player/aos-AVP#278]
Latest versions play 1080 files poorly - issue clearly visible on scenes where the camera is moving.
Tested on Sony TV.

**Comment by courville** [comment]
Is this a regression? Nothing has changed on the way MTK is treated currently.
When camera is moving quickly it could be linked to frame drop related to TV refresh rate not matching video frame rate cf. https://github.com/nova-video-player/aos-AVP/wiki/Aspect-ratio,-display-modes,-refresh-rates
Otherwise please provide sample (or exact filename that could be fetched) so that I can reproduce on a Sony TV.

**Comment by JJD2K** [comment]
I switched to MXPlayer and video plays fluently there - not a media (bad file) problem.
I do not remember the file, but I will let you know.

**Comment by courville** [comment]
Please provide concrete file examples even complete filenames that I will fetch. Timestamp of when the problem occurs will help too. I am sure your file is ok, it is to investigate what could lead to this problem.

**Comment by JJD2K** [comment]
I think this is related to frame rate calculation or maybe a performance issue, but on 1080p should not be.

I do confirm that the issue exists in NOVA and the same file plays perfectly FLUENT in ARCHOS.

Maybe you have enabled MOTION+ or whatever is named on your TV - frame interpolation, soap opera and you do not see it.

I sent you the file on your email, but this issue is present on most 1080p files that I played recently. I was using NOVA to play 1080p in the past, but now that looks nasty too.

I am sorry to be a pain in the ass, but things go in the wrong direction with the player - bad 1080p, subtitles issues....what is the benefit of switching to NOVA from ARCHOS?

I would emphasize again that in my opinion you should ignore mobile phones/tablets and focus on Android TV and tv boxes as these are becoming popular and there are not many players yet and you can catch the market share. This is just my opinion of course.
If I had the TV SHOW list and network support of NOVA with the playback performance of MXPLAYER that would be the best app ever.

Thank you for your work on this project though... I hope you can fix things soon.

P.S. I do not think this issue is related to SONY TV.....

P.S.2 - I read your article about refresh rates and aspect ratio, but I guess there is a way to match the refresh rate in the player code even if the frame rate is different - add/repeat a frame, add micro-delay...I have not coded video players, but there should be an "acceptable" way to overcome the problem that will not be noticeable during playback.

I am watching the content in the original aspect ration just to note.
If ARCHOS is playing the same file smooth then the issue should be in NOVA. I hope it is not a big code-change and can be aligned back to how it was or can be repaired.

**Comment by courville** [comment]
Difference between Archos and Nova is a handful of commits there for multimedia: https://github.com/nova-video-player/aos-avos/commits/nova
I could revert all these changes (that are there fore a reason) and track where the regression is.
We are switching to audiotrack audio interface instead of opensles right now could have a positive impact (to check, I will share an apk).
Do you really think I am using motion+?
If you see no benefit in nova and only regressions, you are welcome to stick to the un-maintained version of Archos Video Player.

**Comment by courville** [comment]
Please test this apk https://drive.google.com/open?id=1_jGMREU2q5g2xz-VciLgnnolHvT-brDH and report if it has positive impact with audio passthrough disabled.
I believe that the performance issue is specific to your hardware (at least not present on all) and related to the way we manage sound interface (audiotrak/opensles).
The changes are: 1) use audiotrack instead of opensles for all, 2) do not trust TV softcodec implementation, 3) fix buffer size issue in audio output, 4) disable too often resume point saving that could interfere with perf over poor wifi
Do you confirm that your sony TV is API24+ i.e. above Android 7.0?

**Comment by JJD2K** [comment]
Hello Marc
I do not want to stick to Archos, but Nova is not getting better...of course, I thanked you already for your work, but things that I reported are not fixed - I am providing feedback and trying to help too as you can see.
Thank you for addressing the sound part - I believe it will help a lot, but the above issue is most likely related to something in the video part.
I will test and let you know.

**Comment by courville** [comment]
Since the video playback is driven by audio, I suspect an audio interface management issue.

**Comment by courville** [comment]
Another test that is worth doing is the following.
MXPlayer uses by default plain Android MediaPlayer (platform player) that could on the Sony TV uses some dedicated enhancements that would not be available for other players like nova/archos/vlc etc.
In order to see if it makes a difference you can force nova to use Android MediaPlayer by in the settings of the application selecting multiple times "Force SW decoding" that will trigger an expert menu where you can chose "MediaPlayer Android".
I would be interested to know if with this option you have a better experience.

**Comment by JJD2K** [comment]
Hello
I tested this version and it seems to be performing much better than the one on the play store.
I can not see the jitter problems - I will test more.
The strange thing is that I see no difference making changes to audio/video decoding options. (I restart the playback of the file after I make changes)
The software decoding is impossibly slow of course.
"MediaPlayer Android" works only on the file that I sent you by email and it can not fast forward which happens in MXPlayer too so I guess that is what it is using. Unfortunately I can not get it to work on ANY other file - it displays Loading....sometimes reaches 2% and Nova freezes...maybe you have missed something there - I would be glad to test this if you find what the issue is.

Generally this versions seems faster...I will send you some more titles that I tried.

**Comment by JJD2K** [comment]
Hello Marc
This version is VERY GOOD!!!!!
I am still testing, but it definitely is with the best performance since the beginning of NOVA.
Maybe it is even on par with MXPlayer.

Only once it crashed when I wast rewinding forward in orde to find a heavy scene in a file to test - tv restarted, but I do not rewind while watching content so even if it is a rare bug I do not care about it.

THANK YOU!

**Comment by courville** [comment]
\o/
I hope that the enhancement will work on all the devices... I will put up a beta release on Google Play to be tried out by the current 950+ beta users.

**Comment by JJD2K** [comment]
Thank you again.
Making the "MediaPlayer Android" testable would be interesting too as the integrated TV player is very good on UHD too. If you have time please take a look at it to see why it is not working.

**Comment by courville** [comment]
I thus consider issue closed and I will look at the previous ones opened linked.
Please reopen if need be.

**Comment by JJD2K** [comment]
agreed...just please check whenever you can why "MediaPlayer Android" is not working

**Comment by JJD2K** [comment]
I tried this version on my Samsung s7 and it plays better there too.
It almost manages to play: Sony New York Fashion HDR UHD 4K Demo.mp4
which almost plays on the TV too, but this time it seems to be more of a buffering issue.
With default audio decoding and hardware Mediacodec I do not see the video buffered on the TV. (lighter progressbar not showing). If I copy the file to TV it copies with 10.5 Mb/s which should be fast enough for realtime playback - no WIFI bottleneck.
The "MediaPlayer Android" is working on the S7, but I can not understand why my S7 has a slower copy rate which is not sufficient for this file - 3.5-6.5 Mb/s (MEGABYTES). I will investigate this.

Generally, your changes have very good results and movies that did not play good are playing fine now.

**Comment by fredbcode** [comment]
FI, tried with Philips 'the one" works well, but no sound at all
