### ISSUE TITLE
Project merge MediaLib has many errors

### ISSUE THREAD

**Issue by yangxp108** [nova-video-player/aos-AVP#298]
Project merge MediaLib has many errors, is there a complete project, can you send me, thank you very much

**Comment by courville** [comment]
Nova relies on many repos (not only MediaLib) and you need to follow the instructions there https://github.com/nova-video-player/aos-AVP and get all the repos with` repo init -u https://github.com/nova-video-player/aos-AVP -b nova`
If you provide more details about your request, I can guide you more.

**Comment by yangxp108** [comment]
OK, can you send me a complete project, my email 1638481466@qq.com Thank you very much!

**Comment by courville** [comment]
Uh, it does not work like this. You need to retrieve the whole project following the instructions of the web page I gave you using repo. Sorry this is the only way to keep in sync since the project is changing often.
If you are in China, you need to find ways to get access to github perhaps via static IP or VPN.

**Comment by yangxp108** [comment]
Thank you! I am in China, I have vpn, I try to do it, thank you! Cooperate with you later!
