### ISSUE TITLE
Android TV Screensaver

### ISSUE THREAD

**Issue by JJD2K** [nova-video-player/aos-AVP#310]
Hello
When paused you should allow the Android TV Screensaver to kick in as this may cause burn-in especially on oled.
MX Player when paused allows the screensaver to start.

**Comment by courville** [comment]
Change pushed and related apk published on Google play beta track (v4.38).

**Comment by mschumacher69** [comment]
@courville can this be added as an option please? Because not all users want the screensaver to kick in when inside Nova (Paused video or just on any Nova screen).

So would be nice if you can add it as an option which can be enabled/disabled.

Thanks

**Comment by JJD2K** [comment]
If you do not want screensaver you can disable it from Android options.
You can also set the delay before the screensaver kicks in so I see no point in adding an extra option in ANY application.
Keeping a static image on a screen causes BURN-IN and can ruin your TV screen and the damage can not be repaired. That happens especially quick on OLED.

P.S. I confirm that the changes in the latest version are working perfectly.
Thank you!

**Comment by mschumacher69** [comment]
I want the screensaver (backdrop) on the TV home screen, but I don't want it in Nova. And I have adjusted the screensaver delay to my liking (minimum time) and I don't want to change it.

Plus, my TV is not OLED.

I understand that wanting the screensaver in Nova is your preference, but not all people have the same preferences.

So the only way to satisfy both needs is to add it as an option instead of forcing it on everybody...

**Comment by JJD2K** [comment]
Hello
Burn-IN issue is not only on OLED - it is on ANY display.
Wanting the screensaver is not my preference - the screensaver should kick in for every application that is IDLE - that is by design.
In this case, nova staying on pause or in the movie selection screen without user interaction is considered IDLE and the screensaver should start. 
Imagine that you forget NOVA on pause and go out for hours. When you come back you see that the paused frame is burned on your screen. It wouldn't be a nice experience.

I have not seen this configurable in any Android application, but of course, if the author decides he can add an option for you though I really do not understand why you (or anyone) would want that.

**Comment by mschumacher69** [comment]
I would want that because that is my preference, you cannot force your preference on everyone no matter how right you think you are.

Leaving Nova on the same screen for a few hours is not going to make any damage to my screen, especially that it is not an OLED display. Burn in is not as big of a problem on LCD displays as it is on OLED displays, not unless you leave it on the same screen for days that is and this is not gonna happen because I have set my TV to automatically turn off after 12 hours and I usually manually turn it off before then and I don't leave it in Nova for that long anyways, the max time I would leave it in Nova is 1 hour maybe. Also, burn in is not permanent on LCD displays, unless you've left your TV on the same screen for weeks, just playing anything on the screen after a few hours on a static screen would get it to correct any potential burn in.

When I leave my TV on Nova, I just want it to stay on Nova, period. It's not what you want, it's what I want, this is my TV not yours.

Screensavers kicking in on any idle application is not by design, if it were, @courville wouldn't have had to make a change to Nova to get it to work, it would have worked automatically.

I don't understand why you have a problem with it being an option, this way you can enable it and I can disable it, problem solved...

**Comment by JJD2K** [comment]
:)
I do not have a problem with it being an option - already wrote that. I do not agree with you though, but I do not want to argue either.

Cheers.

**Comment by mschumacher69** [comment]
OK so why all this fuss about it then?? I'm just asking for it to be added as an option, I'm not asking him to disable it for all...

**Comment by mschumacher69** [comment]
What irritates me the most is that when the video is paused and the screensaver kicks in, the video auto resumes when I remove the screensaver, ughhhhh...

@courville can you please make the screensaver optional?

Thanks

**Comment by courville** [comment]
I am against in general to add options.
The issue if I understand is that it resumes the video and it should not.

**Comment by mschumacher69** [comment]
That's right.
