### ISSUE TITLE
4.46 - External subtitles completely missing

### ISSUE THREAD

**Issue by JJD2K** [nova-video-player/aos-AVP#325]
The latest version displays that subtitles are present in the VIDEO INFO screen, but during playback trying to select them the subtitles selection list is empty.
Most likely related to the other similar subtitles issues I reported in a separate thread, but now no subtitles can be loaded anymore.

**Comment by courville** [comment]
Are you sure that the subtitle is a supported one? PGS is not supported. I can still play with 4.46 subs.

**Comment by JJD2K** [comment]
Yes not a single external subs file is listed for my entire library - testing with the ones that were loading and working before this update.
Only integrated subtitles are working.
Very unpleasant situation. :(

**Comment by courville** [comment]
OK since the recent changes made "should" not have had any impact on this part and that I unfortunatlely cannot reproduce on phone/tablet/androidtv, I will request your help to get an aligned configuration that is highlighting the issue.
I tried the following configs: local storage/samba share folder/movie.mkv folder/movie.en.srt folder/movie.fr.srt folder/movie.srt and 3 subs are detected and played correctly (I can also navigate between these subs).
Please do not hesitate to share files with me (software@courville.org).
Thanks.

**Comment by JJD2K** [comment]
Hello
Thank you very much for looking into this.
I sent you sample files and configuration settings. 

As you can not reproduce it, maybe it is related to the encoding and the issues that I reported before when some subs files were not listed.
Please note that this is not related to file formats or names as nothing is changed except the Nova version - files that were listed before are now missing. 
Definitely it should be a change in the subtitles routines that you made or maybe you altered or commented something while testing/developing.

Thank you again for the prompt response.

**Comment by JJD2K** [comment]
This is a very weird issue and it resolved by itself.
I will try to track this down if it happens again and report.
Sorry for wasting your time.
