### ISSUE TITLE
Dolby Vision doesn't work

### ISSUE THREAD

**Issue by kristofferR** [nova-video-player/aos-AVP#383]
I just tried two Dolby Vision files with the latest Google Play release, and neither displayed DV.

File 1 (No HDR10):
https://sylvan.apple.com/Aerials/2x/Videos/SE_A016_C009_HDR_20190717_3m30s_HDR_4K_HEVC.mov

File 2:
http://media.developer.dolby.com/DolbyVision_Atmos/mp4/P81_GlassBlowing2_1920x1080@59.94fps_15200kbps_fmp4.mp4

File 2 played in HDR10 mode, but File 1 just had weird colors.

Both files trigger DV properly on other Exoplayer apps like MiXplorer and IPTV Extreme.

I'm using an Nvidia Shield Pro 2019.

**Comment by courville** [comment]
Are you using the adaptive framerate option?
I noticed it too but only when using this option.

**Comment by kristofferR** [comment]
No, I just use default settings from a fresh install. I confirmed now that the adaptive framerate option isn't enabled.

Did you get DV working with the files listed above?

**Comment by courville** [comment]
Indeed it requires more work. Will look into it.

**Comment by phhusson** [comment]
This extremely crude patch works on both samples mentioned in the first commit:
https://gist.github.com/phhusson/d2dcfe685af303ac2d85e8ecbc87f2cd

This can't be merged, because a fallback from DolbyVision decoder to HEVC decoder needs to be implemented.
Also this has been tested exclusively on HEVC, not H264.

Exoplayer reference to see the quirks that might be needed:
https://github.com/google/ExoPlayer/pull/5438/files

**Comment by phhusson** [comment]
it's possible to add `&& acodecs_is_type_supported("video/dolby-vision", 0)` in `stream_parser_ffmpeg.c`, but this poses the issue of isolation, because stream_parser_ffmpeg.c shouldn't call android-specific calls

**Comment by courville** [comment]
File 2 tested to work on chromecast with google tv (need to select match dynamic range to content in display settings).

**Comment by courville** [comment]
Seems that some people have still some issues with DV.
Please check comment on https://github.com/nova-video-player/aos-avos/commit/a24c7e4111b14b0f674f2aa7c2fd58935464cd3e too.

> With this patch I am able to play all MP4, MOV and TS samples from https://kodi.wiki/view/Samples on my Nvidia Shield. However, the MKV samples from https://www.makemkv.com/download/dvtest/ did not play correctly. It seems MKV support requires a patched version of FFmpeg (e.g. https://github.com/quietvoid/FFmpeg). I have tried a custom Nova Player build using this FFmpeg and was able to play the MKV samples.

TODO: investigate kodi's branch https://github.com/quietvoid/FFmpeg/commits/release/4.4-kodi and more specifically quietvoid/FFmpeg@0aaf8ea and check if it is not included in incoming 4.4.1 release.

**Comment by mcirsta** [comment]
I've used the latest version of Nova Player and had problems with a DV file in a mkv format. The colors were off with purple and green.
  Would be great if we could get support for this as otherwise this player served me very well.
 The hardware I'm using is a TV box ( generic ) with Amlogic S905X3.

**Comment by courville** [comment]
Just compiled version 6.0.xx with 4.4-kodi latest branch of ffmpeg fork mentioned above as suggested by @Tyaap available here https://drive.google.com/file/d/1wbZokxWSCsGNNkk6cMLSFFdcCK9UxyM2/view?usp=sharing
@HDGuy, @mcirsta @kristofferR and @dhlavaty please test and report if it yields any improvement.

**Comment by mcirsta** [comment]
Thanks. For me it didn't fix the issue. I do think though that it might be an Android issue. The SOC itself should support this DV but I'm not sure the Android that's on it has this support. 
 Could that be the case ? Any way to detect if indeed this DV is supported on you hardware and OS combination ?

**Comment by Tyaap** [comment]
This new build fixed the issue I had with MKV support. All the Kodi sample files played back fine on my Nvidia Shield.

**Comment by Tyaap** [comment]
NB: Using a Nvidia Shield Pro 2019 and an LG CX. I also have the adaptive framerate option enabled.

**Comment by phhusson** [comment]
@mcirsta  Dolby Vision require specific HW support, the tvbox oem must have paid Dolby Vision licensing specifically. S905X3 can support Dolby Vision only if this license has been paid. Do you know if that's the case?

(Chromecast with Google TV or Freebox Player Pop are examples of Amlogic s905x* devices actually supporting Dolby Vision)

Edit: It could be possible to provide some kind of software DV decode support to HDR10, but this would require GLES processing, which is not possible on S905X3 because it is really not powerful enough. Only realistic target would be nVidia Shield 2015, not sure that's very useful. Another way would be to be able to force HDMI output to BT2100, but that'd be 100% device-specific

**Comment by courville** [comment]
OK created own nova ffmpeg fork including nova-video-player/FFmpeg@348f149 merging dovi fixes from https://github.com/quietvoid/FFmpeg/commits/4.4-MatroskaBlockAdd
