### ISSUE TITLE
Choppy playback on x265 1080p videos

### ISSUE THREAD

**Issue by mschumacher69** [nova-video-player/aos-AVP#404]
I've been experiencing choppy playback when playing x265 1080p videos.

Not sure if this is due to hardware limitations on my Android TV (Sony 4K TV) or if it's Nova.

You can test with the following video:
Aquaman.2018.IMAX.1080p.BluRay.x265-RARBG

**Comment by Pentaphon** [comment]
Have you tried other players like VLC and Kodi? It's probably your TV because those shrunken videos from that site run fine in everything I use including Nova on my FireTV and Nova on my Android phone and tablet. 

You may want to tell us which model TV you have so we can find the chipset it uses. I'm sure other people with your TV can't play x265 that well.

**Comment by Pentaphon** [comment]
@mschumacher69 @courville I have stumbled across the solution to this issue while having a massive framedrop issue with a similar file. 

It seems that the RARBG file the OP told us to test with (which seem to be very widely used online by people who torrent from that site) is somewhat at fault because according to this post:

>If you read through Moritz Bunkus’ Post Here 11. He explains the technical nature of the problem, apparently the MP4 files are missing a ctts atom (frame offset table), which in itself is not a fatal error, but appear to be relied upon in many cases.

It seems that because Nova Video Player is one of the players that relies on this, playing such RARBG files results in stuttering. You can find more discussion of this exact issues with these specific files at the following thread.

https://forums.plex.tv/t/example-of-stuttering-hevc-playback-on-apple-tv-4k/558255/62

And more technical discussion of the issue here:

https://gitlab.com/mbunkus/mkvtoolnix/-/issues/2777#note_315725406

It seems the workaround for this issue is to remux the mp4 file to mkv using the latest version of mkvtoolnix. 

Or the OP can just grab an updated version of his torrented file, or another copy of the movie elsewhere.
