### ISSUE TITLE
[Feature Request] V6 Beta Make Animations section an option

### ISSUE THREAD

**Issue by ian1182** [nova-video-player/aos-AVP#435]
Could you consider making the appearance of the Animations section a selectable option. That then allows some flexibility in how an individual wishes to present the list of videos.

Can you also explain what criteria is used to decide if a video falls into the animation category. For example would "The Simpsons" be TV or animation or both?

**Comment by courville** [comment]
For now it is not considered to have animations an option simply because it would impose a complex logic to switch between loaders and result in a complex code to maintain and test.

The criteria used to decide if a video falls into the animation category is based on the tvdb or tmdb scrape genre.
There is a distinction made between animation movies and tv shows.
The animation row contains one tile for animation movies, one for animation shows.
All animation  movies/shows are removed from the tv series and movies rows.

**Comment by ian1182** [comment]
OK
