### ISSUE TITLE
Resume does not work 

### ISSUE THREAD

**Issue by lys1980** [nova-video-player/aos-AVP#451]
Last play store version, Sony Kd48A9 (2020). I stream MKV movies via SMB. If I use external movie player apps it works correctly, but not with  nova player

**Comment by courville** [comment]
I unfortunately cannot reproduce. Could you please check that when exiting the viewing of the movie that you have on your SMB share there is a .movie.archos.resume.xml file and its content (for the last played timestamp)?

**Comment by courville** [comment]
OK I start to think what is causing the issue. Could you try disabling external video player so that nova video player plays the video directly without prompting for a possible player?
When selecting nova to play a video as external video player it does not know about resume points or subtitles since it is not intended to be used as an external player for nova application itself.

**Comment by courville** [comment]
Closing after long period of inactivity. Reopen if needed and after checking that the issue has not been reported already.
