### ISSUE TITLE
Animation row lists every single episode of shows

### ISSUE THREAD

**Issue by ghost** [nova-video-player/aos-AVP#471]
I like using rows, however, if I activate it for animation the row lists every single episode there rather than just the show itself like it is for normal TV shows.

**Comment by courville** [comment]
Since all categories have changed migrating from tvdb to tmdb, what you describe could be a consequence of this migration if you have not fully rescrape all your video collection. At this point with 6.x version, I would recommend to perform a fresh install.
Unfortunately there is no easy migration process for movie/tvshow categories especially with the various translations/locales given the former implantation of the feature.
Please let me know if the issue is still there after fresh install and scrape.

**Comment by ghost** [comment]
Did a completely fresh install and made sure not to process nfo files. Issue persists and the app also crashes on me (Chromecast) when using the rescrape all option in the preferences.

**Comment by courville** [comment]
Yep you are right sorry I misread your issue.
Fresh install does not require to do the rescrape all since it will scrape all once.
Crash noted:
```
java.lang.IllegalStateException: Couldn't read row 0, col -1 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
	at android.database.CursorWindow.nativeGetLong(Native Method)
	at android.database.CursorWindow.getLong(CursorWindow.java:542)
	at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:77)
	at android.database.CursorWrapper.getLong(CursorWrapper.java:131)
	at android.database.CursorWrapper.getLong(CursorWrapper.java:131)
	at com.archos.mediascraper.AutoScrapeService$3.run(SourceFile:461)
```

**Comment by courville** [comment]
Proposed resolution: list animation shows (not episodes) and animation movies only.

**Comment by ghost** [comment]
Issue fixed on my end with newest build.
