### ISSUE TITLE
When activating all rows, still TV Shows tiles are active until new refresh

### ISSUE THREAD

**Issue by courville** [nova-video-player/aos-AVP#476]
![Screenshot_1630847215](https://user-images.githubusercontent.com/242843/132128018-8e848fa7-af4d-4606-8b2e-6fc05291d28b.png)

**Comment by Pentaphon** [comment]
Not sure if this is related or not but when I enable "show all" for movies, TV and animations, they often do not show up immediately when I open Nova but rather, show up a second or two later after the default UI displays, as if the setting is being applied every time I open Nova instead of being permanently applied. I expect it to immediately "show all" when I open Nova, not show up after a slight delay when opening Nova.
