### ISSUE TITLE
10-bit x265 files always default to Software Decoding and look washed out on Snapdragon 460 device

### ISSUE THREAD

**Issue by Pentaphon** [nova-video-player/aos-AVP#515]
I have a device where Nova always fails to hardware decode 10 bit x265 files. Allow me to show you two screenshots from a Moto G Play (2021) phone which runs a Snapdragon 460 using Nova v6.0.28. I suspect the phone's stock firmware has buggy decoders.

One is mpv with flawless playback and correct colors. The other is a clean install of Nova, with choppy playback and washed out colors.  MPV is reporting that hwdec is using used, while Nova says it is using software decoding, meaning it is using ffmpeg. Why Nova can't use hardware decoding on this 10 bit HEVC file, I have no idea. Here is a clip of the video I posted in the screenshots in case you want to play it on your devices and compare to mpv. https://gofile.io/d/eTxqEJ

This is just 1 example I have because this happens on literally every 10 bit x265 file played with Nova on this device. I even have the same problem when trying to play the 10-bit, x265 test files from https://jell.yfish.us/ on Nova.

I've tried other players besides mpv, such as VLC, OPlayer, etc and they all hardware decode it just fine like mpv does. Why is Nova not able to hardware decode on my device but every other player can?

![Screenshot_20211017-121753](https://user-images.githubusercontent.com/49374058/137642187-cea33880-5fd9-4ac2-9dbd-f1f16bb2141d.png)
![Screenshot_20211017-121428](https://user-images.githubusercontent.com/49374058/137642189-bda57417-e451-4b56-baf8-1469a3467c0e.png)
![Screenshot_20211017-122452](https://user-images.githubusercontent.com/49374058/137642195-2ad39cb5-869d-4792-8831-866a86d764f2.png)

**Comment by courville** [comment]
Just tried a couple of the 10b HEVC files (jellyfish and the one you provided) and on my pixel6 it works (hw decode).
Any chance you could post the adb logs and especially the avos ones (native multimedia engine of nova)?
It could provide an idea of what upsets nova.
Hope there is since it works with other players.

**Comment by Pentaphon** [comment]
Here you go.
[log.txt](https://github.com/nova-video-player/aos-AVP/files/7656321/log.txt)

**Comment by Pentaphon** [comment]
@courville get anything useful from my log?

**Comment by courville** [comment]
Browsed through the logs briefly and catching relevant multimedia part via `cat log.txt  | grep -i -E "avos|mediacodec|omx|audio" | sed "s/^[^ADVWEI]* //g"` reveals that there is a problem indeed with your device for decoding HEVC in hardware causing nova to fallback to swdec:
```
E OMX-VDEC-1080P: Extension: OMX.google.android.index.storeANWBufferInMetadata not implemented
E OMX-VDEC-1080P: Extension: OMX.google.android.index.configureVideoTunnelMode not implemented
E OMX-VDEC-1080P: Extension: OMX.google.android.index.useAndroidNativeBuffer is supported
...
E OMX-VDEC-1080P: OMX_COMPONENT_GENERATE_HARDWARE_ERROR
E OMX-VDEC-1080P: ERROR: Sending OMX_ErrorHardware to Client
E OMX-VDEC-1080P: OMX_COMPONENT_GENERATE_HARDWARE_ERROR
...
E NdkMediaCodec: sf error code: -38
```
It might be a nova issue handling the hwcodecs since other players apparently manages it well.
No regarding the washed out colors with ffmpeg, I cannot tell yet.
For going further int he analysis, I will need some help from multimedia gurus like @nnoury.

**Comment by Pentaphon** [comment]
> For going further in the analysis

Here's my codec list from this device here just in case you guys need it later

[moto codecs.txt](https://github.com/nova-video-player/aos-AVP/files/7699022/moto.codecs.txt)

**Comment by Pentaphon** [comment]
Closing this issue because it is a phone and I will be replacing this hardware with something much better this year.
