### ISSUE TITLE
Video Buffer

### ISSUE THREAD

**Issue by JJD2K** [nova-video-player/aos-AVP#53]
Please add option for configuring video buffer.
Playing heavy 4k over network can jump to high mbps at times causing interruptions and bad stutter.

**Comment by courville** [comment]
Are you using Ethernet connectivity or Wi-Fi?
I had many complaints that turned out to be Wi-Fi perf related that got solved by moving things around (5GHz, shield poor Wi-Fi, metallic objects moved doing shadowing, etc.).
I am not sure modifying the buffer size is the solution.

**Comment by JJD2K** [comment]
Hello
No the issue is not with WI-FI.
Sony TV is limited to 100 mbps on cable and theoretically to 733mbps over wireless.
My configuration is working steady reaching 230mbps over wireless.

What I suspect is - the SOC is on its edge when playing 4K and also lots of CPU is used for such fast WIFI transfers.
I can see this in KODI where there is a real-time debug info where I can look at the dropped frames and network buffer. I have set 75 megabytes buffer which at times reaches to zero on very heavy scenes even wit the 230megabits performance of my WIFI.

I test WIFI with 
WIFI SPEED TEST running a server on my local machine.

https://play.google.com/store/apps/details?id=com.pzolee.android.localwifispeedtester&hl=en


So believe me if it is easy to add a buffer will be GREAT.

Thank you!

**Comment by courville** [comment]
On 60GB 4k video, I usually have a 67Mbps video stream (yes average not peak).
Recent enough Wi-Fi can cope with this at small enough distance from the Access Point (due to adaptive rate and modulation. Whatever Wi-Fi technology at a distance you go down as low as 2Mbps).
I understand your KODI buffer setting but for me this is a symptom of a bad network connectivity.
I have no problem watching such movie on Ethernet or locally and CPU load remains small on TV.
This indicates that jcifs perf is good enough as well thus this rules out an SMB overhead issue.
Now let's get back to your problem.
Point of clarification: the Wi-Fi speed test you run, do you confirm that it is from your TV that you are running the application and thus you get a 230mbps displayed there from the TV?

**Comment by JJD2K** [comment]
Hello 
Yes the server is on PC and the client is on TV. I understand what you explain (about wifi), but that is not the case - I get  steady 230mbps on TV and 480-560mbps on my laptop.
AC68U is a very stable strong dual core unit at 1.2 GHZ. (newer hardware revision)
In any case it is a good idea to have a network buffer as user network may get overloaded or as you describe there may be interference, rate modulation etc.
67mbps is very low for 4k vidoe - those usually are around 100mbps and on heavy scenes can go well oabove that.
I played with SPMC yesterday and was astonished to see that it has very good performance - both cores stay at about 50% on a 4k movie - not stutter, but though CPU does not go to 100% on very heavy scenes (many small detail) it still skips frames. This makes me think that the hardware decoder reaches its maximum.
Anyway I do not know what decoders XPMC and MXPlayer are using, but they play much better any 4k both x264 and x265. (The issue with MXPlayer as I pointed though is that it has no buffer too so it pauses to load every few seconds)

If it is easy to add some debug information overlay like the one in KODI/XPMC/Youtube it will be easy to identify where the bottlenecks are. Try pressing the key "i" while playing a movie inside KODI or XPMC if you do not know what I am talking about.

Anyway in all case it is a MUST in my opinion to have a buffer when streaming from network sources.

**Comment by courville** [comment]
Yes it is a must and this is why there is already two layers of buffering on nova or Archos video player: one on the player itself and second on the network side.
All video players use the Android platform HW codecs (i.e. MXPlayer and XPMC).
There is no plan for now to add debug video overlay since it can be done using the console and adb via a dedicated cli interface.

**Comment by JJD2K** [comment]
Yes I see 4k without HW decoding is impossible even on a strong CPU.
I guess all those tools have different implementations as they handle same files differently.
Making the buffer size configurable would be good, though it seems more of a decoding performance issue.

P.S. Thank you for your detailed feedback!

**Comment by courville** [comment]
For me 4k playback issue is not related to buffer, let's close this topic and treat it here https://github.com/nova-video-player/aos-AVP/issues/54

**Comment by JJD2K** [comment]
maybe not always, but it is related.

**Comment by JJD2K** [comment]
please make buffer size configurable - it will be easy to test or just make it larger.
I use 75 MB buffer in kodi and it is ok.

**Comment by ng4ever** [comment]
I built my own mobile local Wi-Fi portable 40 TB NAS just for this. 0 buffering with high quality 4k videos. 

Wish there was a video player for all devices that would prebuffer a little more or keep buffering as much as possible while streaming. 

Never going to happen. 

Was tired of cellular data on networks not being good enough. 

Home internet and Wi-fi is fine though.

**Comment by courville** [comment]
You can tweak buffers in nova's advanced settings (several clicks on force software decoding option).
