### ISSUE TITLE
[Bug]: Series title shows with and without year

### ISSUE THREAD

**Issue by luis-barreira** [nova-video-player/aos-AVP#672]
### Problem description

Nova video player started adding the year to the title of some of my series. It does not happen on all the series, only some. Sometimes when new episodes are added they are added in a different way to the existing ones, resulting in two entries for the same series: one with the year appended to the title and another with just the title.
I've had it occur to me both ways (with and without the year added to the title), so I could not figure out any pattern why this is happening. It started happening with the new version, prior to that no series had the year appended to its title.

### Steps to reproduce the issue

Rescrape some episodes or add new episodes to an existing series.

### Expected behavior

The episodes belonging to the same series should all be added to the same series. Also the year should not be appended to the series title.

### Your phone/tablet/androidTV model

Mi TV Stick / Mi Box 4

### Operating system version

Android 9 / 10

### Application version and app store

6.0.71 (20220623.1933) from Google Play Store

**Comment by courville** [comment]
Hi, thanks for reporting. Note that as highlighted in FAQ and release notes and app update toast, nova v6 switched to tmdb instead of tvdb for TV shows media information retrieval and as a consequence it is strongly encouraged to rescrape from scratch your overall video collection. 
It should solve your problem.
Now the explanation: it happens that shows can have the same name (reboots etc.). In order not to merge shows, if a show is detected with another ID from the current show, the first air date is happened. Only first original shows should not have a date appended. It has been tested to work as a global strategy. And it solved bug reported in other threads.

If in your case it does not solve your issue please report complete file names causing problems.

**Comment by luis-barreira** [comment]
I have already rescraped my entire collection several times.

Some errors:

I have some episodes and specials of "Blackadder", the episodes are all named "Blackadder SXXEXX Episode title [File info]", and the specials are named "Blackadder S00EXX Episode title [File info]". If I rescrape (I just did it now to confirm the results), some of the special episodes are assigned to "Blackadder" and the normal episodes are assigned to "Blackadder 1983".

I have some episodes of season 2 of "Only Murders in the Building", all named "Only Murders in the Building S02EXX Episode title [File info]le", episodes 1 and 2 are assigned to "Only Murders in the Building 2021" and episode 3 is assigned to "Only Murders in the Building".

I normally use tinyMediaManager to rename all episodes, the pattern used for episode names is:

${showTitle} S${seasonNr2}E${episodeNr2} ${title} [${videoFormat}.${videoCodec}.${audioCodec}]
