### ISSUE TITLE
Video file parses but doesn't play

### ISSUE THREAD

**Issue by mjnewton** [nova-video-player/aos-AVP#796]
I've got a bunch of TV episodes that won't play. Nova parses them fine - works out the file details, audio codec etc - but when I attempt to play them I get a few screen refreshes but am then dumped back into Nova again.

Here's an example file:

https://www.newtonnet.co.uk/temp/BlueyS02E01.mp4 (~58MB)
(Renamed from the original so it might not fetch the TVDB info correctly)

I'm running v6.0.81 on a Firestick (tested with same results on both a 4K and non-4K version). Having posted on [Reddit](https://www.reddit.com/r/NovaVideoPlayer/comments/102i177/a_few_files_no_longer_playing/) someone confirmed it played fine for them (running v5.15) and indeed I can play it without issue using players on other devices.

I appreciate I am not giving much to go on here. Would a logcat extract help? If so, anything in particular to pull out or should I just dump the whole lot here?

**Comment by mjnewton** [comment]
To update, the user c0m1cs over on the [Reddit thread](https://www.reddit.com/r/NovaVideoPlayer/comments/102i177/a_few_files_no_longer_playing/) that confirmed it playable on v5.15 also kindly tested the same file on some other versions which appears to suggest a possible regression:

v5.15 - Plays
v6.0.71 - Plays
v6.0.76 - Doesn't play
v6.0.81 - Doesn't play
v6.0.93 - Doesn't play

**Comment by courville** [comment]
OK thanks for the report and narrowing down the versions that plays it. I will test.

**Comment by Pentaphon** [comment]
This is a very poorly standardized encode so I'm not surprised it is proving difficult to play. The mp4 container has been improperly remuxed so the format is still showing as mpegts and thus throwing out an major FileExtension_Invalid  error on v6.0.93.  I remuxed it to mkv using https://mkvtoolnix.download/ and the mkv plays perfectly on v6.0.93. 

@mjnewton You just have to remux all your episodes properly using mkvtoolnix and your whole collection will play just fine on everything. The issue is whatever tool you or the original encoder used to remux to mp4. I think whoever did it might have just improperly renamed .ts files to mp4.

**Comment by mjnewton** [comment]
Thanks @Pentaphon, I'll look to fix it at this end. It was my encode and as it seems to be a one-off (as in the whole series is the same but I haven't seen it with anything else) it's probably not worth looking into further from Nova's perspective, particularly if the video file in this instance is 'broken'.

**Comment by Pentaphon** [comment]
> It was my encode

Ah then I suggest you consider finding a better encoding toolkit because whatever you are using is not properly packaging the files. mkvtoolnix may be all you need for now but in order to eliminate that 2nd step of remuxing all your episodes next time you encode, you should replace your existing encoder with something more modern. 

Go with something highly rated from https://www.videohelp.com/software/sections/video-encoders-h264-vc1?orderby=UpdatedVersion and you should be ok.

**Comment by mjnewton** [comment]
Apologies, I meant to type it *wasn't* my encode!

**Comment by mjnewton** [comment]
I'll close this now as I don't think it warrants any further attention. Thanks for the initial response @courville and the diagnosis @Pentaphon .
