### ISSUE TITLE
[FEAT]: Option to disable DolbyVision

### ISSUE THREAD

**Issue by coolllman** [nova-video-player/aos-AVP#800]
### Description

I have sheld tv pro 2019 and its support dolby vision, but my tv support only hdr10, and when i play hdr+dolby mix mkv, hdr don't work, nova player the best, and only this problem don't make me quit from vimu player (in this player, this option work great), thank you

P.s. sorry for my bad english
Update: test all mkv with hdr+dolby in kodi, hdr works good, but nova player better, any chance to fix it?

**Comment by courville** [comment]
Looking at https://github.com/google/ExoPlayer/issues/9794, it seems that nova could have an option to disable dolby vision codec by rejecting them in `CodecDiscovery` so that `isCodecTypeSupported` would report in avos `stream_parser_ffmpeg:_parse_format` that it needs to switch to another codec.

Could be useful for TVs not supporting DOVI. Perhaps DOVI could be disabled too at platform level in global Android settings on some platforms.

**Comment by coolllman** [comment]
Wow, its great))

**Comment by courville** [comment]
@coolllman, I just plugged by shield 2019 (not pro) and in order to get DOVI you need to specifically request this display mode in the shield Android "Settings > Device Preferences > Display & Sound > Advanced display settings > Custom display mode and select any mode labelled “Dolby Vision Ready”."
When not selecting a DoVi display mode, my TV stays with normal colors without DoVi triggered.

Now this is for bluray dolby vision content (typically movies) but for tv shows I get funky green/purple colors and exoplayer trick will not help here.

Can you please provide the full video file name (including codec/resolution/DV etc.) on which it does not work in nova and it works with vimu player?

**Comment by coolllman** [comment]
Its about 20 mkvs, all dolby vision + hdr10 mix mkv, when tv don't have dovi, its goes to hdr10, in kodi and vimu when plays this mkv, my lg tv switch to hdr,  in nova play, tv not switch to hdr and stays in sdr. In vimu if i enable dolby vision option, tv don't switch tv to hdr the same as nova, disable dolby vision setting in vimu and tv switch to hdr10.
Sample:
https://disk.yandex.kz/i/8x7WPHUjXMmclA

**Comment by courville** [comment]
TODO: fix avos throwing an exception while calling `CodecDiscovery` in `avos:android_codec:acodecs_is_type_supported`.

**Comment by courville** [comment]
@coolllman thanks for sharing the samples, once the code is complete, I will give it a try.
Sample shared is DoVi two layers (el = extended layer in `ffprobe`) thus there is hope.
Method proposed will not work with single layer DoVi files.

**Comment by coolllman** [comment]
Courville big thank you for your hard work and awesome media player!

**Comment by courville** [comment]
OK tested to work on the shield. Will be there in next release.

**Comment by coolllman** [comment]
Thank you, will wait next release.

**Comment by courville** [comment]
Pre-release to test available here https://github.com/nova-video-player/aos-AVP/releases/tag/v6.0.94

**Comment by coolllman** [comment]
Thank you very much, all work great!
