### ISSUE TITLE
[Bug]: Traditional Chinese interface gets online Simplified Chinese subs

### ISSUE THREAD

**Issue by markvlenvision** [nova-video-player/aos-AVP#805]
简体中文显示错误

### Problem description

在线获取字幕选择的是简体中文，但界面显示是繁体中文。
可能是mapping文件映射错误。

<edit>google translate:
The option to obtain subtitles online is Simplified Chinese, but the interface displays Traditional Chinese.
It may be that the mapping file is mapped incorrectly.
</edit>

### Steps to reproduce the issue

字幕设置中选择简体中文，选择一部电影，选择“在线获取字”，字幕下载完成后显示是繁体中文。

<edit>google translate:
Select Simplified Chinese in the subtitle setting, select a movie, and select "Get Words Online". After the subtitle download is completed, it will be displayed in Traditional Chinese.
</edit>

### Your phone/tablet/androidTV model

hk1 box

### Operating system version

Android 9

**Comment by Galaxyjie** [comment]
I have tried several versions, and I have encountered this problem, hoping to fix it

**Comment by courville** [comment]
Perhaps this is an error in my code indeed, but I will need a bit of help here like the one I ask for solving https://github.com/nova-video-player/aos-AVP/issues/1129 for TMDb.

For opensubtitles, the official languages supported are defined as two-lettters code ISO639-1 https://api.opensubtitles.com/api/v1/infos/languages and the relevant parts are for Chinese:
```
{"language_code":"zh-tw","language_name":"Chinese (traditional)"}
{"language_code":"zh-cn","language_name":"Chinese (simplified)"}
{"language_code":"ze","language_name":"Chinese bilingual"}
```
I should thus be using the correct codes. I will investigate and see if the requests are well made to the site when trying to get subtitles and report back here later today.

**Comment by courville** [comment]
OK I checked the requests and it seems ok:
```
https://api.opensubtitles.com/api/v1/subtitles?languages=zh-tw&order_by=from_trusted%2Cratings%2Cdownload_count&tmdb_id=108978&moviehash=f3265e6f6ea51726&season_number=2&episode_number=6
```
I.e. the `languages=zh-tw` is passed for Traditional Chinese. It should thus get the right subs unless opensubtitles serves Simplified Chinese instead of Traditional Chinese.
Please check as well that you have selected in nova settings Traditional Chinese as the subs to download.

**Comment by courville** [comment]
And to be thorough, tried in Simplified Chinese too (perhaps it was the issue after all) and it seems ok too:
```
https://api.opensubtitles.com/api/v1/subtitles?languages=zh-cn&order_by=from_trusted%2Cratings%2Cdownload_count&tmdb_id=108978&moviehash=e1add89c58d0a5e9&season_number=2&episode_number=7
```
I.e. the `languages=zh-cn` is passed for Simplified Chinese. It should thus get the right subs unless opensubtitles serves Traditional Chinese instead of Simplified Chinese.
Please check as well that you have selected in nova settings Chinese (i.e. Simplified Chinese) as the subs to download.

**Comment by courville** [comment]
See https://github.com/nova-video-player/aos-AVP/issues/1228 and https://github.com/nova-video-player/aos-AVP/issues/1129 for new developments.
