### ISSUE TITLE
[Bug]: Problem downloading subtitles 

### ISSUE THREAD

**Issue by scatolo** [nova-video-player/aos-AVP#830]
### Problem description

Hi, if I try to download the subtitles directly from the player it can find them in the language I need but after that I select the one I need but then it is not selectable because it has not been downloaded. I also entered the opensubtitles credentials but I didn't solve it.

### Steps to reproduce the issue

Go to any content and try to download subtitles 

### Your phone/tablet/androidTV model

Oppo Reno 6 Pro

### Operating system version

Android 13

### Application version and app store

6.0.97 GitHub

**Comment by baxax** [comment]
It is a same problem on my machine -android tv box T95 Max+
"cant find subtitles"
-but on OpenSubtitles websites subtitles are there... I'm talking about Croatian and Serbian subtitles.

**Comment by Bigboy-thijs** [comment]
Same issue here: Mibox4 (AndroidTV)
Dutch subtitles available for download but not able to select
.

**Comment by Bigboy-thijs** [comment]
The same issue with external subtitles (srt). System recognises the subtitles but while playing the movie, subtitle is not selectable.

**Comment by courville** [comment]
@TomiScatto please specify the language you use.

@baxax, Croatian is there but not Serbian, I am adding these language.

**Comment by scatolo** [comment]
@courville the language is Italian

**Comment by Maurs9** [comment]
I have same issue with an Android Tv when downloading the subtitles for the movies on a external HDD. 
Note that the subtitles can be downloaded for the movies on a USB flash drive.
But also the download subtitles from VLC works for HDD.

**Comment by courville** [comment]
OK thanks for the feedback. I understand now that it happens on local storage and we are hitting the Android restrictions introduced in the 'R' migration. In order to function properly nova would need `android.permission.MANAGE_EXTERNAL_STORAGE` (cf. https://github.com/nova-video-player/aos-AVP/issues/336). Some other players have it like vlc, mx player, etc. but nova has not been granted it yet. I will appeal again to google to see if they are more mercyful this time (cf. https://www.reddit.com/r/androiddev/comments/rmgdis/how_come_vlc_is_allowed_to_use_manage_external/).
If not, I will try to figure something else.

**Comment by courville** [comment]
Subtitles hdd download should be fixed in next release.
Note that next release will properly display subtitle track language which will help identifying subtitles tracked where subtitles are "FORCED" i.e. containing almost no subtitles (cf. https://www.rev.com/blog/subtitles-blog/what-are-forced-subtitles) which can lead to the perception that subs are not working. Moreover only subs not forced in locale language will be selected by default.
In addition, I have added the possibility to download subs in all the languages supported so far by opensubtitles (there were some missing before).

pre-release available on github to test.

**Comment by baxax** [comment]
> Subtitles hdd download should be fixed in next release. Note that next release will properly display subtitle track language which will help identifying subtitles tracked where subtitles are "FORCED" i.e. containing almost no subtitles (cf. https://www.rev.com/blog/subtitles-blog/what-are-forced-subtitles) which can lead to the perception that subs are not working. Moreover only subs not forced in locale language will be selected by default. In addition, I have added the possibility to download subs in all the languages supported so far by opensubtitles (there were some missing before).
> 
> pre-release available on github to test.

Thanks, that is a very good information! Ty a lot for your effort! :)
