### ISSUE TITLE
[FEAT]: Self-Updater on GitHub version

### ISSUE THREAD

**Issue by warmoans** [nova-video-player/aos-AVP#944]
### Description

A self update function would be useful on Android TV when using GitHub version.

**Comment by Pentaphon** [comment]
This request might not come because Github releases are mostly pre-release versions, so in the meantime, you can use this https://play.google.com/store/apps/details?id=com.esaba.downloader to update your Github version. I personally use it to test new releases. Just put the releases page in the favorites on this app and you can easily update Nova with your remote.

**Comment by courville** [comment]
Not sure it works on Android TV but this works on my phone https://github.com/ImranR98/Obtainium

EDIT: This is not a self update though.
I am not planning to implement a self update based on github for now for many reasons (should be the store purpose,  there are also different signatures between the f-droid/playstore releases etc.).
